### ISSUE TITLE
Lock vehicle camera, oil slicks and a bullet

### ISSUE THREAD

**Issue by diamondo25** [gta-chaos-mod/ChaosModV#106]
This combination seems to make your camera really shaky when going left or right, almost nauseating.

**Comment by Last0xygen** [comment]
The problem here, is that the 'Lock Camera' effect has to be executed every frame to function properly.
The 'Oil Trails' (and other effects) have "WAIT(0)" inside their OnTick methods. As all effects are called synchronously this delays the execution of the 'Lock Camera' Tick-Method.
I don't know what the best solution would be. 
Executing them in seperate threads may help but i don't want to start that without getting feedback.
What do you think, @pongo1231 ?

**Comment by pongo1231** [comment]
@Last0xygen Could definitely be one way to avoid the whole script from pausing when invoking `WAIT`.
