### ISSUE TITLE
If possible I think u should like crop a photo a of his snowy screensaver and when fake crash happens put it over for a second or  few 

### ISSUE THREAD

**Issue by McGrady4Favre** [gta-chaos-mod/ChaosModV#1270]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lZevex** [comment]
This mod is NOT exclusively for Matt

**Comment by McGrady4Favre** [comment]
I know but they can give him a ceritan version nvm

**Comment by Mo-xii** [comment]
. The suggestion is not done properly : what is the point of a template if you don't use it and put everything in the title?
. "his snowy screensaver" Even though you say you know the mode isn't only for DarkViper, your way of requesting an effect would suggest otherwise.
. And finally it's a bad idea. I think you're expecting him to believe he had a crash to desktop. But the snowy screensaver is not what he's seeing when the game crashes, only you. This is an OBS scene. His desktop is very different. It would make it even more obvious for him that it's fake.

**Comment by Last0xygen** [comment]
Doesn’t make sense, also doesn’t work for each user.
