### ISSUE TITLE
Suggestion: mode where two effects happen at once

### ISSUE THREAD

**Issue by ProfessorBiddle** [gta-chaos-mod/ChaosModV#146]
A mode that has a longer timer that makes two effects happen at once would be pretty cool, or an effect that makes two other random effects happen.

**Comment by MoneyWasted** [comment]
That does seem like a cool idea though there could be major issues with that such as crashes from effects overlapping like “Obliterate Nearby Peds” mixing with “Teleport Everything to Player”. Would be fun regardless and I would like to see that implemented.

**Comment by JustTunerYT** [comment]
So, what I expect to be added is marker "Number of effects happening at once" and, if enabled, "Random effects happening at once". About timer, I think this one is a bit useless, because we can set by own, regardless how many effects will happen. To not raise chance of crash, we can set maximum to somewhere in 5-8 effects at once

**Comment by joshuax8** [comment]
I believe this is basically implemented with the Meta effects now, I think this one could be closed.

**Comment by SeanMirrsen** [comment]
Yeah, the Combo Time metaeffect already handles this one. It only happens occasionally, but I believe you can set it to be permanently on in the settings.

**Comment by Last0xygen** [comment]
Already implemented as the „Combo-Time“ metaeffect.
