### ISSUE TITLE
[Effect Suggestion] Need for Slow

### ISSUE THREAD

**Issue by DesolateScorch** [gta-chaos-mod/ChaosModV#1585]
**Name of effect**
Need for Slow, Need for Slowness

**Duration if timed effect (long or short timed?)**
Same amount of time as Need for speed 

**Effect Description**
It’s the polar opposite of need for speed, cannot exceed 40 percent of top speed of current vehicle

**Comment by SeanMirrsen** [comment]
The problem, as it were, with this effect, is that a valid tactic is to stop.

In fact it's more or less preferable to just stop and wait it out, rather than deal with the effect.
Which is why last time it was suggested, I suggested that the punishment be changed to something less severe than exploding. Such as, getting a wanted level. So that the player can still play, but has to balance going at max speed against the threat of getting a wanted level.

And yes, it's a duplicate. #828

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/828

**Comment by RosyMiranto18** [comment]
Why not call it Speed Limit instead?
