### ISSUE TITLE
More Fake Crash options

### ISSUE THREAD

**Issue by diamondo25** [gta-chaos-mod/ChaosModV#1820]
I've had ideas about the Fake Crash effect, mainly:
- use PlaySound for alert sound (crash) https://github.com/gta-chaos-mod/ChaosModV/issues/175#issuecomment-733405016
- use ShowCursor to show waiting cursor
- maybe some render effect to fade out the screen
- ShowWindow(SW_HIDE) to remove the window completely, or SW_SHOWMINIMIZED and then SW_RESTORE to get it back.

**Comment by kolyaventuri** [comment]
FWIW we used to have the alert sound, and did away with it because that's not typically what happens when GTA crashes. 

As for using SW_HIDE, thats been suggested multiple times (see #1638, #1272, #1372, #1103, and so on). I have explored how to do that, but to no avail quite yet. Any calls to the window methods end up _actually_ crashing the game, but I just haven't had time to go back and debug it
