### ISSUE TITLE
[Effect Suggestion] Witness Protection

### ISSUE THREAD

**Issue by LilCuteli** [gta-chaos-mod/ChaosModV#1853]
**Name of effect**
Witness Protection

**Duration if timed effect (long or short timed?)**
120 Seconds

**Effect Description**
I know there's already a "Witness Protection" effect, but this is different.
What if the current "Witness Protection" effect becomes "Fake Witness Protection" and the agents around don't block or deviate bullets?
And the new "Witness Protection" basically spawns an "FIB Buffalo" or an "Unmarked Cruiser" with FIB agents inside or even Dave Norton?
And those agents protect you from danger and do not count as cops? Also protect you from enemies except the police.
Of course they will follow you with their car if you're driving or walking around.

**Comment by JustTunerYT** [comment]
It's basically "Scooter brothers/Bus bois + Spawn random companion". I don't write codes, but i think it would be problematic to create such effect, as they should follow you in their own car and defend you in their own or outside of their car. Oh, and mod have to know, if the vehicle is an air vehicle to spawn those agency companions into your vehicle. But i think it would be funny to see such effect. Also, since we already have "Witness Protection", we should give it another name. My idea is "LS Reboot"

**Comment by Last0xygen** [comment]
This would just be „spawn random companion“ with a car
