### ISSUE TITLE
"Spawn Random Vehicle" effect causing occasional crash

### ISSUE THREAD

**Issue by Lucas7yoshi** [gta-chaos-mod/ChaosModV#2]
Just creating this to let you know, if you have a discord i can contact to let you know about stuff that'd be nice

But yeah when having the spawn random vehicle on it crashes my game, i reverted the code in my local copy of it to what it was before my pull request and it still happens. 

![image](https://user-images.githubusercontent.com/28872095/75644855-c3f47a00-5c11-11ea-8021-0e29593fe764.png)

Can't be my changes since this is run with a compiled version of previous changed, maybe you can understand the error more than i can.

**Comment by Lucas7yoshi** [comment]
To make things weirder i reset my entire config and disabled twitch mode and only enabled random spawns and it is now not crashing me. Maybe i didn't properly rebuild it? not sure.

**Comment by pongo1231** [comment]
Already aware of it, usually seems to happen after the effect has been triggered a few times. I'm not sure why exactly that happens as it just fetches the model hashes from game memory and stored them in a list. It's not because of some weird broken model either as the crash happens randomly and seems to occur while accessing the list directly.

Also yes my discord is pongo1231#6909

**Comment by pongo1231** [comment]
Should be fixed in 25cee5179600d8120b47f22a16643e16c58b0c98 now, feel free to comment if issue still persists
