### ISSUE TITLE
[Suggestion] Feature: Metaeffects

### ISSUE THREAD

**Issue by SeanMirrsen** [gta-chaos-mod/ChaosModV#236]
It occurred to me that Chaos isn't quite chaotic enough.

As an optional feature, there could be a new class of effect called Metaeffects.

These effects don't mod the game, but rather mod the mod - hence, 'meta'.
By default, it could be set so that once a minute or two, there is a 50% chance of a metaeffect activating, with a standard duration of 30 seconds to 1 minute. The idea is to add metaeffects periodically, but not bombard the player with them.

Metaeffects would include:
- Doubletime/Halftime: For the duration of the effect, the timer runs at double or half speed.
- Combo time: Two effects are picked at next timer threshold instead of one.
- More the merrier: If an effect spawns an object, vehicle, or character, it spawns them twice.
- Calm before the storm: Skip adding effects for next two timers, then add three effects at once on the third.
- I'm sorry what: Hide the timer and active effects display (basically all of the mod's HUD besides the metaeffect name) for the duration.

Among possibly others I can't quite imagine at the moment.

**Comment by OHSHIET** [comment]
That's a really good idea (first mistyped goood, then god, guess this represents it well enough), I was thinking the same (Chaos isn't chaotic enough), and had the same idea about changing the duration, but I just knew it wouldn't fit into the mod's atmosphere with the current effects. However I still think it needs to be implemented one way or another, because right now it's just a massive barrier which restricts us from adding more really interesting stuff.

First idea that came to mind was another bar, but a slow one. This bar would be responsible for metaeffects. For Twitch voting there would be different numbers for choosing metaeffects. however the problem is that there might be too much stuff on the screen and a lot of terminology for people who just want to have fun. Also a lot of metaeffects will be needed for a separate bar (and I guess not only for it, just for more variety...)

**Comment by SeanMirrsen** [comment]
I think that, for several reasons, the metaeffects should not be on their own (visible) timer, and should not be votable.

Firstly, the entire point of the idea is to introduce less predictable variety into the mod. Metaeffects should not activate at predictable intervals, which is why I think there should be a 50% chance of one activating at the cutoff. It both gives the player breathing room, and adds an extra degree of uncertainty.
(which would be a nice positive metaeffect I think, "breathing room", pausing the timer for one cycle)

As an alternative to a second timer, perhaps metaeffects could have a lower chance of activating (20%-ish) on every cycle of the regular timer, as long as there isn't another active metaeffect.

Secondly, there aren't really going to be enough of the metaeffects to make voting interesting. Even optimistically I don't think there will be more than 10 different metaeffects. If you get Twitch picking from three out of ten effects, you just know there won't be much variety at all in the types of effect picked. With so few effects, it's better to have the mod itself randomly pick from the whole list.

**Comment by TheRealAyCe** [comment]
Will Twitch still be able to Vote for "Calm before the Storm"/"Two at once", but their results are saved & stacked (invisible for player) and applied all at once later? With a 15 sec voting duration for "Two at once" to allow chat to select 2 effects?

**Comment by SeanMirrsen** [comment]
I'm guessing for "two at once"/"combo time", Twitch will vote as normal, but instead of picking one most-voted effect it will pick the top two. Or in the case of proportional chances, it will just pick two effects using the probability distribution the voting has resulted in.

Maybe there could be a separate metaeffect called "double whammy", that does do the quick 15-second timers to let Twitch vote on two separate effects, that then drop together.

And maybe "combo time" could do something different, like give choices of predefined pairs of effects, sort of like how Super Run and Super Jump were merged into one effect, but more dynamic. Like combine "Set time to Night" and "Blackout", "Honk boosting" with "All cars honk", "Whale rain" and "Meteor shower", and all kinds of other destructive or silly combinations that you'd sometimes like to see but that never happen naturally because of how rare they are.

For "Calm before the storm", I guess letting the effects be selected as normal, but delay activation until the third timer, would be the most intuitive way to do it. So Twitch would vote as usual for two rounds with nothing happening, and on the third round both that round's selection and the previous two drop at once.

**Comment by OHSHIET** [comment]
If you don't mind me writing suggestions on metaeffects here

- Blessed: The next effect will be a "good" effect. You can make this a lasting effect, so there would be not one effect, but 2+ at least. For Twitch voting, if there are "good" effects in the list, the mod will choose only from them and won't take into consideration other effects: Good, Bad, Good, Random. The mod will pick Random and 2 good effects. If random wins, of course only good effects still, but random good effects. You'll have to adjust the chances, because one bad effect will be gone. If all the effects are not "good", the mod will just choose random. 
- Cursed: The next effect will be a "bad" effect. Everything else is the same.
- Neutral: The next effect will be a "neutral" effect. I now think that it would be better if these effects were lasting, because for Twitch voting it isn't the same.
- Randomized: lasting. Every next timer threshold the mod will choose a random number between x and y (you choose) corresponding for the amount of time before the next effect. lasting effects will now also have random timers. Basically make everything as randomized as possible.
- Rewind: similar to #240, but more implementable. All the timers start going back and previous effects activate. When the top (most important) timer reaches the left corner of the screen, a previous effect activates. For lasting effects, when the timer reaches the "beginning", the effect ends. For usual effects, they will disappear from the list on the right after being activated again. Twitch voting would be disabled for some time (people would still be able to choose the next effect, but it won't happen until the metaeffect ends). When all the previous effects end (the timer can't go back anymore), all the timers start going forward as usual. It's sad though that lasting effects aren't saved on screen in the mod's HUD, it's disappointing for this.

**Comment by OHSHIET** [comment]
Should we now suggest metaeffects in new issues?

**Comment by Last0xygen** [comment]
@OHSHIET Nah, i think you should wait until pongo has time to look at the base-system i created, as that may delay the meta-effects altogether
