### ISSUE TITLE
[Effect Suggestion] Millions To One (DViper reference)

### ISSUE THREAD

**Issue by bigjosh1337** [gta-chaos-mod/ChaosModV#2383]
the suggestion is explained in the youtube clip attached!
https://youtu.be/byj7lFgjSH4?t=345

**Comment by Last0xygen** [comment]
duplicate.........

**Comment by bigjosh1337** [comment]
> duplicate.........

looked through and hadn't seen it anywhere, my bad

**Comment by Last0xygen** [comment]
There's one been worked on:
https://github.com/gta-chaos-mod/ChaosModV/pull/1380

Closed Suggestions:
https://github.com/gta-chaos-mod/ChaosModV/issues/2359
https://github.com/gta-chaos-mod/ChaosModV/issues/2250
https://github.com/gta-chaos-mod/ChaosModV/issues/2168
https://github.com/gta-chaos-mod/ChaosModV/issues/2132
https://github.com/gta-chaos-mod/ChaosModV/issues/2076
https://github.com/gta-chaos-mod/ChaosModV/issues/2008
https://github.com/gta-chaos-mod/ChaosModV/issues/1891
https://github.com/gta-chaos-mod/ChaosModV/issues/1870
https://github.com/gta-chaos-mod/ChaosModV/issues/1668
https://github.com/gta-chaos-mod/ChaosModV/issues/1505
https://github.com/gta-chaos-mod/ChaosModV/issues/1460
https://github.com/gta-chaos-mod/ChaosModV/issues/1421
https://github.com/gta-chaos-mod/ChaosModV/issues/1455
https://github.com/gta-chaos-mod/ChaosModV/issues/680
https://github.com/gta-chaos-mod/ChaosModV/issues/1215
.... and im sure there are several other ones

**Comment by SeanMirrsen** [comment]
> Closed Suggestions:


See, a lot of the time that's the problem. All these suggestions that people keep making, end up closed. And by default the issue search does not include closed issues. People that come in here to suggest things most likely don't know enough about github to even make a distinction between open and closed issues, let alone try to include them in their search.

**Comment by Last0xygen** [comment]
So? We still have to close those issues, can’t let them be open if they’re not open.
I know what you’re trying to say but there’s nothing else we can do. We even try with templates that everyone should follow and ever third request just deletes the whole template and misses crucial information.
So yeah, it’s the sad reality that those request will keep on coming. No offense directed at you, „bigjosh“

**Comment by SeanMirrsen** [comment]
> 
> 
> So? We still have to close those issues, can’t let them be open if they’re not open.
> I know what you’re trying to say but there’s nothing else we can do. We even try with templates that everyone should follow and ever third request just deletes the whole template and misses crucial information.
> So yeah, it’s the sad reality that those request will keep on coming. No offense directed at you, „bigjosh“

We can do a thing though. Back in the old forum days we used to call it an MTR thread. Monthly Topic Rotation, it'd be a pinned thread containing all the commonly started (and shut down) topic themes that nobody wanted to see again because they kept popping with regularity at least once a month (hence MTR).

In the context of suggestions here, we can make an official "open" suggestion issue titled in an obvious way like "COMMON SUGGESTIONS LIST - If you found this, your suggestion may be inside, take a look!", and it'd contain all the usual culprits like cougars, other Matto references, pedestrian model changes, animorphs/peyote, teleports to impossible locations, GTA Online related stuff, etc. It'd just exist as a keyword catch-all for commonly suggested things, explaining that all of those things are repeatedly suggested and just *DO NOT WORK*.

We could have a similar open issue with a list of all *existing* effects, with a similar descriptive title, so that people stop suggesting things that already exist as effects. It'd also conveniently act as an up-to-date effect reference, with names and descriptions.
