### ISSUE TITLE
Add negative weighting to recent effects

### ISSUE THREAD

**Issue by byhemechi** [gta-chaos-mod/ChaosModV#25]
I suggest that effects have a weight parameter added, which incremented a new effect is added to the player and zero'd out every time it occurs. This would make duplicates *much* more unlikely to happen.

I can have a  go at writing this tomorrow, but my cpp isn't the greatest.

I've thrown together some dart as an example of what I mean

```dart
import 'dart:math';

class Effect {
  Effect(this.weight);
  
  double weight;
  
  void tick() {
    weight += .1;
  }
  
  String toString() => "Effect with weight $weight";
  
  void onChosen() {
    weight = 0;
  }
}

List<Effect> effects = [Effect(1.0), Effect(2.0)];

Effect pickEffect() {
  var totalWeight = .0;
  effects.forEach((e) => totalWeight += e.weight);
  
  var rand = Random().nextDouble() * totalWeight;
  
  for(var i = 0; i < effects.length; ++i) {
    if(effects[i].weight > rand) return effects[i];
    rand -= effects[i].weight;
  }
  
  return null;
}

void main() {
  for(var i = 0; i < 5; ++i) print(pickEffect());
}
```

**Comment by pongo1231** [comment]
Good idea, should be easy to implement too. Instead of setting weight to 0 it'd probably be better to set it to some low value instead so there's still a (very low) chance of an effect occuring two times in a row (unless the option to prevent effects from happening twice in a row is enabled, in which case it'd be set to 0) but overall this will add much more variety in the effects that are chosen by the mod.

**Comment by pongo1231** [comment]
Weights of all effects will increment by their set multiplier once an effect is triggered and the triggered effect will have their weight reset to either their multiplier or 0 depending on if the option to prevent effects from happening twice in a row is enabled.
