### ISSUE TITLE
Effect: Activate a random cheat code

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#271]
Activates a random cheat code https://www.gamesradar.com/gta-5-cheats/

You can exclude the ones that already have their separate effects.

**Comment by Terrain2** [comment]
almost all of them are already in the mod, i think it'd be a better idea to just add the remaining cheat codes as chaos effects
TURTLE - HESOYAM (also gives money but that can be fixed with Poor Boy)
PAINKILLER - Invincibility
FUGITIVE -+2 Wanted Stars and 5 Wanted Stars
LAWYERUP - Never Wanted
POWERUP - that's not in the mod, but it doesn't seem to cause any chaos
SKYDIVE - that's not in the mod, but it should be
LIQUOR - Drunk
CATCHME, HOPTOIT - Super Run & Super Jump
GOTGILLS - i don't think that's in the mod, but it should rather be merged with Super Run & Super Jump, maybe as "Super Run, Jump & Swim"?
SKYFALL - Launch Player Up
FLOATER - Low Gravity
HOTHANDS, HIGHEX - Explosive Combat
DEADEYE - Dead Eye
INCENDIARY - that's not in the mod
SLOWMO - 0.2x Gamespeed and 0.5x Gamespeed
MAKEITRAIN - several effects, but Disco Weather does all of them
SNOWDAY - Slippery Vehicles
JRTALENT - doesn't apply to story mode
EMPDROP - this one is explained badly at the link you attached, but it doesn't seem to resemble anything in the mod

Then there's a bunch of vehicle spawns, some of which have individual modules, others don't but might still appear via Spawn Random Vehicle, so i count about 4 cheat codes that aren't already in the mod, i think they could just be added as chaos modules rather than "pick random cheat code", since that seems to be basically the whole idea of the mod anyways, just with a lot more possible outcomes than just the cheat codes that are built into the game

**Comment by Last0xygen** [comment]
Mod already implemented most of them, the rest is only vehicle spawns
