### ISSUE TITLE
[Effect Suggestion] Call from Agatha Baker

### ISSUE THREAD

**Issue by KazMotor** [gta-chaos-mod/ChaosModV#2902]
**Name of effect**
Potential name(s) for the effect:
- This is Agatha
- [Agatha]

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long (like a minute or so)
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
ITS:
Long unskipble call from aghata baker 
https://youtu.be/_nuQsneeZqY

Matto hates it. Its nice meme

**Comment by Last0xygen** [comment]
No effects for just specific streamers.

**Comment by KazMotor** [comment]
> No effects for just specific streamers.

but you did "blimp strat". lol.

**Comment by Last0xygen** [comment]
Because jumping out of a blimp itself is a good idea imo, forcing the player to listen to something is not lol

**Comment by ParthNaik14** [comment]
> No effects for just specific streamers.

That guy literally carries the marketing of chaos mod. He's the unofficial brand ambassador of chaos mod for gta 5. Most of your users are because of that said streamer. PC has around 50 milion players(without the free give aways on epic and hiven that gta 5 sold 150 mil copies), out of which 75% play online(includes FiveM), estimated 23% just own the game and are frustrated of playing the same game again and again and only 2% players play story mode. That makes 1 million players who play the story mode, around 7000 speedrun(official speedrun.com numbers) the game and around 200k play with the chaso mod(gta5-mods.com numbers) and others play it for miscellaneous reasons. Matt has 980k subs on YT and 700k followers on twitch, adding this effect is a win-win situation for your mod, there's absolutely no loss in adding this effect. There's absolutely no reason why not to put this effect. It will become an instant meme.

**Comment by NLferdiNL** [comment]
This could be pulled away from DarkViper by just having the effect pick a random GTA Online property phone call.

For example, Ron calling for the hangar. Lazlow and the nightclub etc. This would include Agatha but not be limited to like the original suggestion.

**Comment by Last0xygen** [comment]
> This could be pulled away from DarkViper by just having the effect pick a random GTA Online property phone call.
> 
> For example, Ron calling for the hangar. Lazlow and the nightclub etc. This would include Agatha but not be limited to like the original suggestion.

DuPlIcAtE https://github.com/gta-chaos-mod/ChaosModV/issues/1119
