### ISSUE TITLE
[Effect Suggestion] Im Drunk

### ISSUE THREAD

**Issue by D3DH4CK3R** [gta-chaos-mod/ChaosModV#3228]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Player Has A Drunk Vision And Hard To Drive

**Comment by SeanMirrsen** [comment]
This is already an effect.

@Last0xygen I once again propose that a list, with descriptions, of all effects that currently exist in the mod, in text form for people who don't have the mod or the game, be created. So that it can then be linked in the issue creation template. Specifically for the purpose of reducing the occurrence of this.

**Comment by Last0xygen** [comment]
@SeanMirrsen history has shown that the majority of duplicates are simply because it was not searched at all. Providing a list with current effects may help, but only the small part suggesting already implemented ones. The majority of duplicates are effects already suggested. And keeping the list of current effects up2date… meh 😅
