### ISSUE TITLE
[Effect Suggestions] A bunch of ideas

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#349]
So, i have several ideas. if you dont wanna read them, thats alright. Only implement the ones you think could be worth it. Have a nice day :-)

**High fps**

Long effect; 90 seconds

It locks your fps high, example 120

**Low Fps**
Long effect; 90 seconds
It locks your Fps at 30

(I have no name for this one)
Short effect; 20-30
An effect that deletes any entities you touch. Like 'Midas touch', but money doesn't spawn.

**Thorns**: 
30/90 seconds
A percentage of any damage you take from an NPC will be reflected back to them.

**Tire pop**: 
30/90
Pops a single tire every 5-15 seconds. Makes driving hard without spamming or killing tires instantly.

**Full ammo**: 
Instant
Gives full ammo to all weapons in inventory

**No ammo**: 
Instant
Removes all ammunition from player

**Spawn super car**: 
Instant
Like 'spawn random vehicle', but only cars in the 'super' category have a chance of spawning

**Spawn special vehicle**: 
Instant
Like 'spawn random vehicle', but only vehicles in the 'special' category have a chance of spawning.

**Spawn random aircraft**: 
Instant
Spawns a random plane or helicopter

**The sniper**: 
Instant
Removes all weapons from player, and gives a sniping rifle with a couple hundred rounds.

**Gta online**: 
Instant
Removes all weapons from player, and gives all online-only weapons.

**Fast regen**: 
30 seconds
Makes player regenerate 5x as fast, and make remove limit to full healt instead of half.

**No regen**: 
30 Seconds
Stops the player from healing.

**Infinite ability**: 
30/90 seconds
Gives player infinite special ability power.

**Money men**: 
Instant
Turns every loaded entity (peds, cars, traffic light, ect) except the player into money bags.

**Chill weather**: 
30/90 seconds
Slidy peds and slidy vehicles. Maybe also snow and a light blue color to seem more chilly.

**Hot sauce**: 
20-30 seconds
Makes the player run super fast, but if they stop running they get set on fire.

**Comment by Terrain2** [comment]
how would "High fps" work? you can't exactly lock the fps to never go below a certain threshold

the midas touch delete thing could be called "Thanos"? that would also imply a specific effect when they disappear, and not just pop out of existence

Make Thorns 90 seconds and allow it to go again during its own duration, and when it's applied it stacks to "Thorns II" and "Thorns III", with 15%, 30% and 45% damage reflected to the attacker respectively to the level. Also, damage the player by 2 more points, in order to stay true to the minecraft enchantment, or alternatively if the player has armor, make the effect last until their armor is broken and allow it to stack up to level 7 at a 100% chance of inflicting the damage on the enemy and the armor, at which point it cannot be applied again until the armor breaks.

"Machine guns" is just rapid fire + loose triggers?

rename Fast Regen to Regeneration, because you described the minecraft potion effect of that name

"Chill weather" is just a combo of other effects?

"Hot sauce" is a good idea, but maybe make it part of Need for Speed? that effect doesn't do anything on foot, and kills you if you bail, perhaps it could use the same timer system but require running on foot at no particular speed?

**Comment by anto4440** [comment]
Ok, i can see your concern with 'High Fps', it was meant to be an effect you could turn off in settings if the effect would be without use.

'thanos' as the name... idk man, im not the one programming it, but i wont stop the creator.

Im not trying to stay true to the minecraft enchantment. i just thought the name was appropriate.

'Machine guns' is on me, for forgetting to remove it.

Regeration is alread a thing in GtaV, so 'Fast regen' is way better. Again, it has nothing to do with minecraft.

Meh, I dont really think 'Hot sauce' should be changed

**Comment by Terrain2** [comment]
i think the idea with thorns was pretty nice, it would make the effect very unique and i think that's a good thing

i didn't mean to change "Hot Sauce", just merge it with Need for Speed, because that effect is lacking anything on foot - maybe since you die if you exit a vehicle in need for speed, the effects could be a single one as far as the randomness and voting system is concerned, and then when it's actually picked, depending on whether you're on foot or in a vehicle either need for speed or hot sauce could be applied (and if you get in a car that would count as stopping to open the door or whatever, and you burn)

perhaps that could be applied to many similar effects that only work on foot or in a vehicle (i.e. explode current vehicle and suicide, which are already combined in Fake Death which plays one or the other depending on if you're in a vehicle, or sometimes plays no fake effect and just the fake wasted screen) - but some effects, such as "Set Player Into Random Vehicle Seat" already do different things if you're in a vehicle (in a vehicle it sets in a random vacant seat, if the vehicle is full does nothing, without a vehicle it sets you into a random seat in a random vehicle), and as such i thought it could be the same effect

**Comment by Last0xygen** [comment]
Please split up into separate requests

**Comment by anto4440** [comment]
oh, please...

Den man. 22. mar. 2021 kl. 11.49 skrev Last0xygen ***@***.***

**Comment by Last0xygen** [comment]
You don’t need to if you don’t want to 😅

**Comment by anto4440** [comment]
Fine, ill do it. But if you write 'Dupe of #349'...

Den man. 22. mar. 2021 kl. 12.32 skrev Last0xygen ***@***.***

**Comment by anto4440** [comment]
Actually, scratch that. Every one of these effects have already either been implemented, suggested again or closed.
