### ISSUE TITLE
[Effect Improvement] Fake Crash

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#351]
I noticed, that most crashes happen without any crash window with sound (like in current version).

What to improve: Add second Fake Crash possibility which causes game freeze and game mute for 1-1.5 seconds

**Comment by Terrain2** [comment]
i noticed this too, and i actually never experienced a crash with the noise in the chaos effect until recently, but suddenly, it was a case of the boy who cried wolf, with the mod having given fake crashes and i thought "yeah it's just a fake crash", but no, it wasn't a fake crash, my game had actually crashed and that nose happens when the mod causes scripthook to crash, not a fault in the game - i don't think this should be implemented, because i honestly think that making users think "ah it's just a fake crash" until suddenly it actually crashes with that noise is much more jarring than making the fake crash emulate the crash they're used to

**Comment by JustTunerYT** [comment]
> i noticed this too, and i actually never experienced a crash with the noise in the chaos effect until recently, but suddenly, it was a case of the boy who cried wolf, with the mod having given fake crashes and i thought "yeah it's just a fake crash", but no, it wasn't a fake crash, my game had actually crashed and that nose happens when the mod causes scripthook to crash, not a fault in the game - i don't think this should be implemented, because i honestly think that making users think "ah it's just a fake crash" until suddenly it actually crashes with that noise is much more jarring than making the fake crash emulate the crash they're used to

Um, actually this effect meant to troll players, whenever its fake or not. I wanted to make the "fake game crash", in which it would be done in next to "fake mod crash", but mod chooses, which one Will be played

**Comment by Last0xygen** [comment]
This already is in the mod now 😊
