### ISSUE TITLE
[Effect Suggestion] Real Fake Crash

### ISSUE THREAD

**Issue by we-script** [gta-chaos-mod/ChaosModV#3550]
Real Fake Crash

**Duration**
- [ ] Long
- [ ] Short
- [X ] No duration

**Effect Description**
This affect will take a screenshot of the users desktop, and when this is selected, it will make GTA 5 change into that picture, but first it will wait a few seconds with the game frozen normally (Like the normal fake crash), then it will display the picture, in the game, making it look like the game has crashed, after a few seconds it will then go back to the normal game and show up in the recent effects tab as "Real Fake Crash"

**Comment by MoneyWasted** [comment]
Any effect that would involve interacting with anything out side of the game such as accessing the users desktop environment will NOT be added.

This is mainly due to privacy concerns of streamers but is also due to false flags by anti-viruses.

This effect will also require more work than just "showing a picture" as creating textures during runtime is difficult.

**Comment by ReiDaTecnologia** [comment]
Yeah it's a shame but real crash aren't something that will be added officially.

**Comment by we-script** [comment]
> At first that looks like a great idea, but most people wouldn't want their desktop shown to the public unless you hide their icons, in which case the streamer or anybody else would know when it's a real crash vs when it's a fake one.
> 
> So I don't think this one should be added sorry :/

Well, for example but DarkViperAU has a desktop with no icons, so the real crash would work there if they just hid the icons.
