### ISSUE TITLE
[Effect Suggestion] Spawn enemy space ranger

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#490]
**Name of effect**
Potential name(s) for the effect
 
Spawn enemy space ranger

**Effect Description**
Description of the effect; what should it do?

 Spawn enemy space ranger
with windowmaker weapon or unholy  hellbringer
---------------------------
here the ped id 
u_m_y_rsranger_01

**Comment by anto4440** [comment]
We dont need any more spawn vehicle or ped. Do we? A lot of people says we dont.

**Comment by Last0xygen** [comment]
I don’t think we do 🤷 
Already covered with „spawn random enemy“

**Comment by TheRealAyCe** [comment]
Though it might be cool to have easy-to-add templates for this random enemy (and ally), in additon to completely randomizing them. That way a lot of suggestions could be put in that effect without creating an entirely new effect and debalancing the amount of spawn effects.

**Comment by Last0xygen** [comment]
The problem is that you’ll have 10, 20, 30 spawn effects then having the same chance to get chosen than any other effect. Having 3 spawn effects as options are imo not entertaining.
While I understand that several spawn effects may be funny I think they should be kept to some minimum

**Comment by SeanMirrsen** [comment]
We already have "spawn random enemy". Perhaps it should have a chance to spawn specific themed enemies, rather than only random pedestrians with weapons. 

Other than that I agree. Impotent Rage, Angry Alien, and Griefer Jesus are fun because they're really unique, and present unique threats. We don't need more variations on "people that shoot you" like Jealous Jimmy, or "people that straight-up murder you" like Griefer Jesus. The random enemies can have those people included, but they don't need their own spawn effect.

**Comment by TheRealAyCe** [comment]
@Last0xygen @SeanMirrsen I'm repeating myself here, but I wasn't talking about adding new effects, but about defining templates to be used in the "Spawn Random Enemy" effect. That way the problem you are describing does not occur, while still providing a way to define "unique" enemies. So "Spawn Random Enemy" has a chance to spawn an enemy from this template list, in addition to spawning a completely randomized enemy.

**Comment by SeanMirrsen** [comment]
Yeah, that's basically what I said. Actually a fair number of effects can have such randomized outcomes. They can even come with their own name, rather than just remaining 'random'. I.e., if "spawn random enemy" triggers a themed enemy it'll say "spawn <themed enemy>". Same with random vehicles that may have specific custom variants, random teleports to all kind of unusual locations, spawning various Obstructively Large Objects, giving random weapons, etc.
