### ISSUE TITLE
[Bug] 5x Timer Speed Last Effect bug

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#640]
https://www.twitch.tv/videos/923473471 ~1:58:00
When 5x Timer Speed finishes, the last effect that is being voted on will be locked, but the timer duration is extended again after voting is closed. Either don't extent the timer duration again, or don't lock voting.

Same thing for x2 Timer Speed.

**Comment by pongo1231** [comment]
Already known issue. Since the voting logic runs on its own process the communication happens through a named pipe which causes a delay between sending and receiving data through it. The mod fetches the voting result 1 second before the voting round ends (to ensure there won't be any lag caused by the voting proxy counting the votes, determining the effect to dispatch and sending that data through the named pipe) so votes after that period won't be counted anymore. Voting rounds can also start at a later time than when the timer bar is reset again (configurable by the user through the `TwitchVotingSecsBeforeVoting` setting) so hiding / greying out the on-screen options makes sense to indicate to the user if a voting round is currently running or if a new one has started.

The problem should be mitigated by e6a802d616832fd3701fe3452a3011e380abdcf8 already, however the default time for users who already configured the meta times will need to be changed manually by the user (or by resetting the config).
