### ISSUE TITLE
Effect suggestion

### ISSUE THREAD

**Issue by YesNoY** [gta-chaos-mod/ChaosModV#654]
**Name of effect**
Formula 1

**Effect Description**
Spawns a race track from GTA online in front of player and puts player in a random formula 1 car from GTA online

**Comment by anto4440** [comment]
The size of the race tacks means that unless your in the ls airport, nothing will really happen from this.

**Comment by pongo1231** [comment]
You can't use open wheel cars in singleplayer since they'll despawn after a short time (if you have a way to bypass this please do message me), also creating a complete race track with props is going to be very messy (either a lot of manual prop spawning or implementing JSON/XML/whatever format parsing for just 1 effect. I don't see it as suitable for the mod.
