### ISSUE TITLE
[Effect Suggestion] Tie Your Shoes

### ISSUE THREAD

**Issue by TahaEfendi** [gta-chaos-mod/ChaosModV#656]
**Name Of The Effect**
Tie your shoes

**Duration**
30 seconds

**Effect Description**
Player ragdolls on random times

**Comment by anto4440** [comment]
I think that name should update, and duration should definitely be set to long. More so, this is one of the effects that instantly could be avoided by simply being in a car. Maybe you could make it so it applies to all npcs, so that everyone risks ragdolling (Maybe 'untied shoes' would then be a better name). Additionally, it would be nice if running signiffically increased your odds of falling. Good effect idea.

**Comment by Last0xygen** [comment]
Already implemented with „I’m tired“, which received a random chance of ragdolling while on foot and steering to one direction while driving

**Comment by anto4440** [comment]
But then we still dont have a way of randomly ragdolling other npcs. I could imagine so many hilarious moments from this.

**Comment by Last0xygen** [comment]
> But then we still dont have a way of randomly ragdolling other npcs. I could imagine so many hilarious moments from this.

Still would be „ragdoll everyone“ with a random timer, right?
Too different from the actual Request, you may create a new request.
As a developer it’s easier to read the top comment to get what the request is, without reading all comments to what it has been changed to over time, Hope you understand. :)

**Comment by anto4440** [comment]
Yeah that makes perfect sense.
