### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by zynophobia** [gta-chaos-mod/ChaosModV#701]
**Name of effect**
Potential name(s) for the effect
Help My SpaceBar Is Stuck
**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
I'd say not very long maybe a minute
**Effect Description**
Description of the effect; what should it do?
Just spams jump

(Basically hear me out I play gta 5 pc when I run I always accidentally press the spacebar to a point I get annoyed at myself for doing it)

**Comment by anto4440** [comment]
First of all, change the name to something other than 'My super cool effect idea'
Second, The layout is really terrible:
**Name of effect:**
Help my spacebar is stuck

**Duration if timed effect (long or short timed?)**
Long (Maybe one minute instead of the usual 90 sec)

**Effect description**
Presses the jump key every frame, making player constantly jump.

Third: The effect isnt all too interesting, just kinda boring.

**Comment by Da-Best** [comment]
this effect is basically useless in cars as cars do not have a jump button so it will only work on foot.
