### ISSUE TITLE
Improve fake crash

### ISSUE THREAD

**Issue by GincCat** [gta-chaos-mod/ChaosModV#820]
Fake crash

instant

improve fake crash,by making it happen at random times and not at the end of the timer

**Comment by Numi43** [comment]
Possible solution for that could be having something like what was proposed for fake Teleport and fake Death - a fake label. It could say nothing then the game would randomly after 6-10s act weirdly, then changing the "Nothing" to "Fake Crash".
Thus you will never be certain if Nothing is indeed nothing.
.

**Comment by lZevex** [comment]
A fake label for every other fake effect isn't needed, and the "Nothing" effect is too rare for people to think it's real if it happens often enough, not to mention the game will never crash because of nothing. Making it happen at random times can work, but still have a chance for it to happen at the end of the timer so sometimes people will think an effect made it crash on top of the other things being activated.

**Comment by TheRealAyCe** [comment]
This is already in the works but I can't find the exact ticket right now. Look for yourself: https://github.com/gta-chaos-mod/ChaosModV/issues?q=fake+crash

**Comment by Last0xygen** [comment]
Already suggested several times without any real solutions to this. Unless someone has a satisfying solution or a good suggestion for this I will close These issues.
The Problem:
Currently you can „guess“ it’s Fake because it’s right after starting a new effect.
But: if you delay it, what will you show instead? If you show something like „nothing“ people will adapt to „it crashes after that nothing effect“
I guess the only „real“ solution would be to make it completely separate from the current voting/timer system, execute another effect instead and delaying the crash for a random amount of time.
But this goes against the whole setup this mod uses just for this one effect, which does not seem like a good solution to me too.

**Comment by lZevex** [comment]
Don't show anything or activate an effect that doesn't kill you instantly or teleport you Meteor Shower, Bus Bois etc., then disable that effect after a few seconds once fake crash is activated, would be very convincing.

**Comment by Numi43** [comment]
There can be like 5 effects that can turn into fake crash and would be temporary.

**Comment by Last0xygen** [comment]
But again, this is completely separate from how effects get handled in this mod.
Not showing anything is major suspicious, would be recognized „immediately“.
Executing anything else for a short period of time could also fail the current mission which should not happen for this effect (don’t you think?)
I guess the best solution right now would be to make it a meta effect so it’s independent of everything else but this removes the effect option for chat. Something to consider 🤔

**Comment by lZevex** [comment]
That's why I suggested an effect like meteor shower, anything that doesn't make the mission fail instantly, then after a few second activate fake crash and disable said effect afterwards

**Comment by lZevex** [comment]
Making it a meta effect wouldn't work for obvious reasons

**Comment by Last0xygen** [comment]
> Making it a meta effect wouldn't work for obvious reasons

Ok, what is the obvious thing I’m missing?

Again, it’s not that easy
* what happens if meteors are already an effect? Duplicate display or extend the current time?
* What happens afterwards? Does the effect get disabled even if it existed before?
* ...

**Comment by lZevex** [comment]
It's not even close to unique and it's just making things complicated for no reason. If the effect is already active (Which doesn't happen often enough that it's a big problem) refresh the timer and change it back after the fake crash

**Comment by Last0xygen** [comment]
That’s not really an „obvious reason“ 🤔 
Making it a meta effect doesn’t make it more complicated but actually easier to implement.

Adding and deducting times is a new feature which doesn’t exist right now.
Faking an effect for a fraction of the normal time is also a new feature new don’t have yet.
