### ISSUE TITLE
[Effect Suggestion] Picture Show

### ISSUE THREAD

**Issue by MrDrJohnny** [gta-chaos-mod/ChaosModV#898]
**Name of effect**
Picture Show

**Duration if timed effect (long or short timed?)**
Short, 30 seconds or less.

**Effect Description**
Game is capped at 1FPS, audio plays as normal. Like a picture show.

**Comment by TheRealAyCe** [comment]
"Mobile Experience"

**Comment by SeanMirrsen** [comment]
I think this kind of thing is usually called a "slideshow".

Actually, I sort of wonder. Can the game be made to frame-advance? Like limit the FPS to 0, and then briefly raise it to 1 so another frame renders, before going back to 0.

Because you could make a "powerpoint presentation" effect, where the game only renders a frame once per click.

**Comment by TheRealAyCe** [comment]
When you reduce the timescale alongside with it maybe?

**Comment by lZevex** [comment]
Pretty sure that making the FPS that low would break the game

**Comment by Last0xygen** [comment]
In the original "Console Experience" i set it to ~15 FPS, which was too annoying (see https://github.com/gta-chaos-mod/ChaosModV/pull/373)
-> increased to ~25
and its already THAT annoying :D 
Making it a "slideshow" / cap at 1fps makes its unplayable until the effect is over, sorry
